name: my_first_triangle
description: "My first triangle, ala OpenGL"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  flutter_gpu_shaders: ^0.2.0
  native_assets_cli: ^0.9.0
  vector_math: ^2.1.4
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - build/shaderbundles/
