name: my_first_triangle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gpu:
    sdk: flutter
  flutter_gpu_shaders: ^0.1.1
  native_assets_cli: ^0.7.2
  xml: ^6.5.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - build/shaderbundles/